name: smontiamo_la_voce
description: Laboratorio interattivo su suono, Fourier, armoniche e formanti.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^7.1.1
  audioplayers: ^6.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
